parameters:
    ngsite.layouts.block.plugin.vertical_whitespace.top:
        none: 'block.plugin.vertical_whitespace.none'
        small: 'block.plugin.vertical_whitespace.small'
        medium: 'block.plugin.vertical_whitespace.medium'
        large: 'block.plugin.vertical_whitespace.large'

    ngsite.layouts.block.plugin.vertical_whitespace.bottom:
        none: 'block.plugin.vertical_whitespace.none'
        small: 'block.plugin.vertical_whitespace.small'
        medium: 'block.plugin.vertical_whitespace.medium'
        large: 'block.plugin.vertical_whitespace.large'

    ngsite.layouts.block.plugin.vertical_whitespace.positions:
        both: 'block.plugin.vertical_whitespace.top_and_bottom'
        top: 'block.plugin.vertical_whitespace.only_top'
        bottom: 'block.plugin.vertical_whitespace.only_bottom'

    ngsite.layouts.block.plugin.vertical_whitespace.sizes:
        lg: 'block.plugin.vertical_whitespace.large'
        md: 'block.plugin.vertical_whitespace.medium'
        sm: 'block.plugin.vertical_whitespace.small'

    ngsite.layouts.block.plugin.background_color.colors:
        white: 'block.plugin.background_color.white'
        black: 'block.plugin.background_color.black'

    ngsite.layouts.block.plugin.set_container.sizes:
        '': 'block.plugin.set_container.regular'
        'narrow': 'block.plugin.set_container.narrow'
        'wide': 'block.plugin.set_container.wide'

services:
    ngsite.layouts.block.plugin.title_icon:
        class: Netgen\Bundle\SiteBundle\Layouts\Block\Plugin\TitleIconPlugin
        public: false
        tags:
            - { name: netgen_layouts.block_definition_handler.plugin, priority: 100 }

# New plugin version: not enabled by default due to backwards compatibility

#    ngsite.layouts.block.plugin.vertical_whitespace_v2:
#        class: Netgen\Bundle\SiteBundle\Layouts\Block\Plugin\VerticalWhitespaceV2Plugin
#        public: false
#        arguments:
#            - "%ngsite.layouts.block.plugin.vertical_whitespace.top%"
#            - "%ngsite.layouts.block.plugin.vertical_whitespace.bottom%"
#        tags:
#            - { name: netgen_layouts.block_definition_handler.plugin, priority: 200 }

    ngsite.layouts.block.plugin.vertical_whitespace:
        class: Netgen\Bundle\SiteBundle\Layouts\Block\Plugin\VerticalWhitespacePlugin
        public: false
        arguments:
            - "%ngsite.layouts.block.plugin.vertical_whitespace.positions%"
            - "%ngsite.layouts.block.plugin.vertical_whitespace.sizes%"
        tags:
            - { name: netgen_layouts.block_definition_handler.plugin, priority: 200 }

    ngsite.layouts.block.plugin.background_image:
        class: Netgen\Bundle\SiteBundle\Layouts\Block\Plugin\BackgroundImagePlugin
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
        tags:
            - { name: netgen_layouts.block_definition_handler.plugin, priority: 300 }

    ngsite.layouts.block.plugin.background_color:
        class: Netgen\Bundle\SiteBundle\Layouts\Block\Plugin\BackgroundColorPlugin
        public: false
        arguments:
            - "%ngsite.layouts.block.plugin.background_color.colors%"
        tags:
            - { name: netgen_layouts.block_definition_handler.plugin, priority: 400 }

    ngsite.layouts.block.plugin.set_container:
        class: Netgen\Bundle\SiteBundle\Layouts\Block\Plugin\SetContainerPlugin
        public: false
        arguments:
            - "%ngsite.layouts.block.plugin.set_container.sizes%"
        tags:
            - { name: netgen_layouts.block_definition_handler.plugin, priority: -100 }

    ngsite.layouts.query.content_by_topic:
        class: Netgen\Bundle\SiteBundle\Layouts\Query\ContentByTopicHandler
        public: false
        arguments:
            - "@ezpublish.api.service.location"
            - "@netgen.ezplatform_site.load_service"
            - "@netgen.ezplatform_site.find_service"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "@ezpublish.spi.persistence.section_handler"
            - "@ezpublish.spi.persistence.object_state_handler"
            - "@netgen_layouts.ezplatform.content_provider"
        tags:
            - { name: netgen_layouts.query_type_handler, type: content_by_topic }
