ngsite_download:
    path: /content/download/{contentId}/{fieldId}/{isInline}
    requirements:
        contentId: '\d+'
        fieldId: '\d+'
        isInline: 0|1
    defaults:
        _controller: "ngsite.controller.download:downloadFile"
        isInline: 0
    methods: [GET]

ngsite_user_register:
    path: /user/register
    defaults:
        _controller: "ngsite.controller.user:register"

ngsite_resend_activation_mail:
    path: /user/activate
    defaults:
        _controller: "ngsite.controller.user:activationForm"

ngsite_user_activate:
    path: /user/activate/{hash}
    defaults:
        _controller: "ngsite.controller.user:activate"

ngsite_user_forgot_password:
    path: /user/forgotpassword
    defaults:
        _controller: "ngsite.controller.user:forgotPassword"

ngsite_user_reset_password:
    path: /user/forgotpassword/{hash}
    defaults:
        _controller: "ngsite.controller.user:resetPassword"

ngsite_content_search:
    path: /content/search
    defaults:
        _controller: "ngsite.controller.search:search"

# Disable eZ Platform built in routes

ez_content_download:
    path: /_error/404

ez_content_download_field_id:
    path: /_error/404

ez_user_register:
    path: /_error/404

ezplatform.user.register:
    path: /_error/404

ezplatform.user.user_register:
    path: /_error/404

ez_user_register_confirmation:
    path: /_error/404

ezplatform.user.register_confirmation:
    path: /_error/404

ezplatform.user.user_register_confirmation:
    path: /_error/404

ezpublishSetup:
    path: /_error/404

_ezpublishLegacyRest:
    path: /_error/404
