services:
    twig.extension.array:
        class: Twig\Extensions\ArrayExtension
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig\Extensions\DateExtension
        public: false
        tags:
            - { name: twig.extension }

    ngsite.templating.global_variable:
        class: Netgen\Bundle\SiteBundle\Templating\GlobalVariable
        public: false
        arguments:
            - "@ngsite.helper.site_info_helper"
            - "@ezpublish.api.repository"
            - "@netgen.ezplatform_site.load_service"

    ngsite.templating.twig.extension.site:
        class: Netgen\Bundle\SiteBundle\Templating\Twig\Extension\SiteExtension
        public: false
        tags:
            - { name: twig.extension }

    ngsite.templating.twig.runtime.site:
        class: Netgen\Bundle\SiteBundle\Templating\Twig\Extension\SiteRuntime
        public: false
        arguments:
            - "%kernel.debug%"
            - "@ngsite.helper.path_helper"
            - "@ezpublish.locale.converter"
            - "@netgen.ezplatform_site.load_service"
            - "@ezpublish.fieldType.ezimage.variation_service"
            - "@?netgen_remote_media.provider"
            - "@?logger"
        tags:
            - { name: twig.runtime }

    ngsite.templating.twig.extension.topic_url:
        class: Netgen\Bundle\SiteBundle\Templating\Twig\Extension\TopicUrlExtension
        public: false
        tags:
            - { name: twig.extension }

    ngsite.templating.twig.runtime.topic_url:
        class: Netgen\Bundle\SiteBundle\Templating\Twig\Extension\TopicUrlRuntime
        public: false
        arguments:
            - "@ngsite.topic.url_generator"
        tags:
            - { name: twig.runtime }
